source "https://rubygems.org"

gem "ruby", "< 2.7.dev" 

gem 'github-pages', group: :jekyll_plugins

# Added at 2019-11-25 10:11:40 -0800 by jhoward:
gem "nokogiri", "<= 1.10.10"
gem "jekyll", ">= 3.7"
gem "kramdown", ">= 2.3.0"
gem 'tzinfo', '~> 1.2'
